FROM postgres:18-alpine AS runtime-amd64
FROM postgres:18-alpine AS runtime-arm64
FROM postgres:18-alpine AS runtime-arm
FROM postgres:18-alpine AS runtime-s390x
FROM postgres:18-alpine AS runtime-ppc64le

# 根据 TARGETARCH 选择对应的运行时镜像
FROM runtime-${TARGETARCH} AS runtime