<template><main class="legal-page"><header class="legal-nav"><NuxtLink to="/" class="brand"><img :src="getLogo()" alt="VoiceHub" /></NuxtLink><NuxtLink to="/login" class="nav-login"><svg viewBox="0 0 24 24"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" /><circle cx="12" cy="7" r="4" /></svg>{{ locale.login }}</NuxtLink></header><section class="legal-hero"><div class="doc-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h9l3 3v15H6zM9 13h6M9 17h4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" /></svg></div><div class="legal-hero-copy"><div class="eyebrow">{{ locale.category }}</div><h1>{{ legalDoc?.name || locale.title }}</h1><p v-if="updatedDate">{{ locale.updated }} {{ updatedDate }}</p></div></section><section class="legal-body"><AppSpinner v-if="loading" /><article v-else-if="legalDoc" class="legal-content"><div class="markdown-body" v-html="renderedContent" /></article><p v-else class="empty">{{ locale.notFound }}</p></section></main></template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import AppSpinner from '~/components/UI/Common/AppSpinner.vue'

import { renderMarkdown } from '~/utils/markdown'
import { useLocale } from '~/utils/locale'
import { useSiteConfig } from '~/composables/useSiteConfig'
const route = useRoute(); const { common } = useLocale(); const { initSiteConfig } = useSiteConfig(); const { getLogo } = useThemeImage(); const legalDoc = ref(null); const updatedDate = ref(''); const loading = ref(true)
const locale = computed(() => ({ category: common.value?.legalPage?.category || '服务条款', title: common.value?.legalPage?.title || '服务条款', updated: common.value?.legalPage?.updated || '最后更新：', login: common.value?.legalPage?.login || '登录', notFound: common.value?.legalPage?.notFound || '文档不存在' }))
const renderedContent = computed(() => legalDoc.value ? renderMarkdown(legalDoc.value.content) : '')
onMounted(async () => { await initSiteConfig(); try { const response = await $fetch('/api/legal-documents'); updatedDate.value = response.updatedDate || ''; legalDoc.value = response.documents?.find((item) => item.slug === route.params.slug) || null } finally { loading.value = false } })
</script>
<style scoped>
.legal-page{min-height:100vh;color:var(--text-primary);background:var(--bg-primary)}.legal-nav{height:68px;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(20px,5vw,64px);border-bottom:1px solid var(--border-secondary)}.brand{display:flex;align-items:center;gap:12px;color:var(--text-primary);font-weight:800;text-decoration:none}.brand img{width:40px;height:40px;border-radius:10px;object-fit:cover}.legal-hero,.legal-body{max-width:832px;margin:0 auto;padding-left:24px;padding-right:24px}.legal-nav{height:84px;display:flex;align-items:center;justify-content:space-between;padding:0 22px;border-bottom:1px solid var(--border-secondary)}.brand img{width:170px;height:58px;object-fit:contain}.nav-login{width:auto;min-width:104px;height:44px;display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:0 18px;border:1px solid var(--border-secondary);border-radius:14px;color:var(--text-secondary);background:transparent;text-decoration:none;font-weight:700}.nav-login svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.legal-hero{display:grid;border-bottom:1px solid var(--border-secondary);grid-template-columns:48px 1fr;column-gap:16px;padding-top:28px;padding-bottom:28px}.legal-body{padding-top:28px}.doc-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:8px;background:var(--info-light);color:var(--info)}.doc-icon :deep(svg){width:25px;height:25px}.legal-hero-copy{display:flex;flex-direction:column;align-items:flex-start;gap:8px}.eyebrow{margin:0;color:var(--info);font-size:14px;font-weight:700;line-height:1.3}.legal-hero h1{margin:0;font-size:30px;line-height:1.15;font-weight:850}.legal-hero p{margin:0;color:var(--text-tertiary);font-size:14px}.legal-content{padding:32px;border:1px solid var(--border-secondary);border-radius:14px;background:var(--bg-secondary)}.empty{color:var(--text-tertiary)}@media(max-width:600px){.legal-nav{padding:0 16px}.brand span{max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.legal-hero{padding-top:40px}.legal-content{padding:20px}}
</style>
